### PR TITLE
Update to using tools from tidyverse: purr and readr to read all file…

### LINKED ISSUE #3: use `readr`
Would necessitate handling of tibbles instead of dataframes, but would solve #1 .

### PR DESCRIPTION
**Pull request by markdunning**
Suggestion to fix #3 by using read_tsv from the readr package in conjunction with purr to read all the files in a directory

### CODE REVIEW

**Comment by katrinleinweber** [comment]
Hello and thanks for this update suggestion :-)

Is it related to https://github.com/katrinleinweber/FAIR-studyGroup/issues/4 by any chance? I'll keep this PR open for that session about updating legacy code.

**Comment by markdunning** [comment]
Not related at all. We were doing a Hacktoberfest session and my Institute, and this seemed like an issue I could help with.

**Comment by katrinleinweber** [comment]
Nice :-) What a cosmic coincidence that I scheduled an event with the same intention for this example on the same day.

**Review by katrinleinweber — APPROVED** [review]
Thank you for getting this started! We had a good workshop session about updating legacy code from this example :-)

**Pull request merged**
